apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vllm
  description: A high-throughput and memory-efficient inference and serving engine for LLMs
spec:
  type: service # can be one of: service, library, website, iac-pipeline
  lifecycle: production # can be one of: experimental, production, deprecated
  owner: team-vital # your existing tech team in Backstage, i.e. team-developer-platforms